name: Vet and test GO code

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Vet GO code
        run: |
          go vet ./...
      - name: Test GO code
        run: |
          go test ./...
